### ISSUE TITLE
Currently examples are not linked to the wordnets

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/gwadoc#10]
I propose we add a macro or two:

Linked to omw 1.0 for now, but can change to omw 2.0 soon:
{%- macro pwn(name, key) -%}
*<a href="http://compling.hss.ntu.edu.sg/omw/cgi-bin/wn-gridx.cgi?synset={{ key }}">{{ name }}</a>*
{%- endmacro %}

And maybe: for named ili links:
{%- macro ilin(name, symbol) -%}
⟪<a href="http://compling.hss.ntu.edu.sg/iliomw/ili/concepts/{{ symbol[1:] }}">{{ name }}</a>⟫
{%- endmacro %}

We could also think of trying to get the name with a language parameter from OMW in the future, not quite sure how, ...

@goodmami  does this look good to you?   I have some examples and would like to get a student to add them in, with links, ...

**Comment by goodmami** [comment]
In general this looks good. We had some issue before with choosing a macro name that doesn't clash with other variables, etc. in the templates. As long as we're careful about that these should be fine.

And, forgive my ignorance, but are named ili links fundamentally different than non-named links, or is the name just optional? If the latter, then I think we can just use the current `ili()` macro but give it a `name` parameter with a default value.

**Comment by gconnect** [comment]
I think this issue has been resolved?
