### ISSUE TITLE
'other' on sense–synset relations

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/gwadoc#20]
The WN-LMF-1.0.dtd has lists for "synset relations" and "sense relations", but it does not distinguish sense–sense and sense–synset relations. According to this repository, there are just 3 sense–synset relation types: `domain_topic`, `domain_region`, and `exemplifies`, although I don't recall seeing this info codified anywhere else.

It seems like the `other` relation, which is a catch-all for undefined relation types, might be appropriate for sense–synset relations as well. Should it be documented as such?

**Comment by fcbond** [comment]
G'day,

On Wed, Jun 24, 2020 at 3:50 PM Michael Wayne Goodman <
notifications@github.com> wrote:

> The WN-LMF-1.0.dtd has lists for "synset relations" and "sense relations",
> but it does not distinguish sense–sense and sense–synset relations.
> According to this repository, there are just 3 sense–synset relation types:
> domain_topic, domain_region, and exemplifies, although I don't recall
> seeing this info codified anywhere else.
>
I think this is based on the fact that these were the only sense–synset
relations we found in PWN3.0.

> It seems like the other relation, which is a catch-all for undefined
> relation types, might be appropriate for sense–synset relations as well.
> Should it be documented as such?
>
I would be happy to add other.



>

-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by gconnect** [comment]
Not sure if this has been handled
