### ISSUE TITLE
It would be good to have a script to build index.lang.html for all languages

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/gwadoc#23]
currently we build by hand:

`python docs/build.py --lang ja html > docs/index.ja.html `

But it would be good to build an index for each `lang` in `gwadoc/doc_LANG.py`.

Maybe a bash script would be easiest?

**Comment by goodmami** [comment]
With the new build action, I just specify which languages to build there and it's done automatically. If we need something more sophisticated we could use the `LANGUAGES` data in `inventories.py`, although I'm forgetting again why "symbol" is included as a language.

**Comment by gconnect** [comment]
I think this issue has been fixed?

**Comment by goodmami** [comment]
I think we've just sidestepped the issue. @fcbond do you still want to automate something here, or is the build action sufficient?

https://github.com/globalwordnet/gwadoc/blob/d66c482bf7f9356121c064d8f95b69c58a38ab92/.github/workflows/build.yml#L24-L28

**Comment by fcbond** [comment]
I think I would like to (at least):

 * change the build script to make docs/index.en.html and then link it to docs/index.html
 * add links in the main doc page to the existing documentation in other languages
