### ISSUE TITLE
We should have a guideline for writing the documentation for a relation

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/gwadoc#24]
This should cover things like how the short definition is written, how to reference, the format of tests and so forth.

**Comment by fcbond** [comment]
Please add this as a new file: `CONTRIBUTING.rst`

As we are writing the docs in rst, using it for the CONTRIBUTING file might help with examples of rst usage.

Here are some ideas:

https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

But I think let's not make the file too elaborate for now :-).

**Comment by gconnect** [comment]
I will work on it

**Comment by gconnect** [comment]
This has been done.

**Comment by fcbond** [comment]
Closed by #37
