### ISSUE TITLE
Normalize short description and short examples

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/gwadoc#3]
Because we want the short definitions and examples to be useful for quick reference (e.g., on tooltips), we should ensure that the short definition is a single short sentence or phrase, not multiple sentences, and the example gives a single easy-to-understand example of the relation.

We should also normalize the way we talk about things, e.g., for `hypernym` we say "a word that is more general than a given word" but for `meronym` we say "Y makes up a part of X". We should be consistent in the way they are described.

Similarly for examples, for `hypernym` we have "animal is a hypernym of dog" but for `meronym` we have "hand/finger".

**Comment by fcbond** [comment]
@glory please check the short descriptions and examples for consistency.

**Comment by gconnect** [comment]
To ensure consistency, which pattern should be adopt for short descriptions and examples to be used across all relations?

Between which should be used;

**Short Description** : "a word that is more general than a given word"
or
**Short description** : "A makes up a part of B". 

**Short Example** :  `manchester <ILIURL/83395>`_ has instance_hypernym `city <ILIURL/81847>`_
or
**Short Example** :  `manchester <ILIURL/83395>`_ has instance-hypernym `city <ILIURL/81847>`_
or
**Short Example** :  `manchester <ILIURL/83395>`_ is an instance hypernym of `city <ILIURL/81847>`_

**Comment by goodmami** [comment]
I think maybe this issue is superseded by #39. Shall we close this one?

**Comment by fcbond** [comment]
Closing as the discussion has moved to #39.

**Comment by goodmami** [comment]
It looks like Francis meant to close this. I'll close it now.
