### ISSUE TITLE
Create Documentations for  Constitutive, Instance Hyponym, Instance Hypernym, Antonym, Equal Synonym,Similar

### ISSUE THREAD

**Issue by gconnect** [globalwordnet/gwadoc#46]
Create Documentations for;
 - Constitutive,
-  Instance Hyponym, 
- Instance Hypernym, 
- Antonym, 
- Equal Synonym,
- Similar

**Comment by goodmami** [comment]
Did #49 resolve the issue? If so, can this be closed?

**Comment by gconnect** [comment]
Yes, #49 resolve the issue.

**Comment by goodmami** [comment]
Great, I'll close it then
