### ISSUE TITLE
is_entailed_by showing incorrect reversed relation

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/gwadoc#76]
The wrong reverse relation is being shown for `is_entailed_by`. It is originally defined correctly:

https://github.com/globalwordnet/gwadoc/blob/ee7a269a2cfa26eb22cc89989048df1f280e4d34/gwadoc/doc_basic.py#L1191

But then the data for `other` incorrectly uses `is_entailed_by` when defining its reverse, thus shadowing the original info:

https://github.com/globalwordnet/gwadoc/blob/ee7a269a2cfa26eb22cc89989048df1f280e4d34/gwadoc/doc_basic.py#L1200-L1207

But what is correct for `other`? Does it have an reverse, or should none be declared?

**Comment by fcbond** [comment]
`other` is used for relationships not otherwise defined, so we can't guarantee that it has a reverse.

I will tidy up the documentation and fix the reverse of `is_entailed_by`.
